// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sviiqwggqhoomomitqvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aWlxd2dncWhvb21vbWl0cXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDQ2NjMsImV4cCI6MjA3MDE4MDY2M30.EFNjh5ANWfrvsybjNcBgaXsttP5erlg0_2HNbX_VrV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});